---
title: "HOMER"
author: "Darragh"
date: "10/29/2019"
output: html_document
---

```{r}

#need to go back and look at which ones to include
#master_importance should be 250k

HOMER_Active <- read.delim("C:/Users/darra/Dropbox/4th_year_project_Darragh_Nimmo/5_Enhancer_Master_Matrix/Output_files/Master_Active.txt", sep="\t",header=T, stringsAsFactors = FALSE)  

tail(HOMER_Active)
HOMER_Active = HOMER_Active[-40881,]


for(i in 1:nrow(HOMER_Active)){
  if(HOMER_Active$Strand[i] == "*" ) {
    HOMER_Active$Strand[i] = "+"
    }
}



#so at the minute it is all active enhancers (40881) by selecting for importance = 4 this will grep out the active enhancers deemed important
HOMER = grep(4,HOMER_Active[,17]) 
HOMER_Active = HOMER_Active[HOMER,] #11303


#HOMER_Active = data.frame(HOMER_Active$Chr, HOMER_Active$Start, HOMER_Active$End, HOMER_Active$ChipPeakAnno_ID, HOMER_Active$Width, HOMER_Active$Strand )




#colnames(HOMER_Active) = c("chromosome", "starting position", "ending position", "Unique Peak ID", "Width", "Strand" )



write.table(HOMER_Active,"C:/Users/darra/Desktop/Project/HOMER_Active.bed",col.names=T,row.names=F,sep="\t",quote=F)




```

```{r}

#Column9 is LNCaP_H3K27ac, So this will grep out the Active LNCaP enhancers as only these will have this mark
HOMER = grep(1,HOMER_Active[,9]) 
HOMER_Active = HOMER_Active[HOMER,] 




HOMER_Active_LNCaP = data.frame(HOMER_Active$Chr, HOMER_Active$Start, HOMER_Active$End, HOMER_Active$ChipPeakAnno_ID, HOMER_Active$Width, HOMER_Active$Strand ) #2303(nrow)

colnames(HOMER_Active_LNCaP) = c("chromosome", "starting position", "ending position", "Unique Peak ID", "Width", "Strand" )

write.table(HOMER_Active_LNCaP,"C:/Users/darra/Desktop/Project/HOMER_Active_LNCaP.bed",col.names=T,row.names=F,sep="\t",quote=F)

##

HOMER_Active <- read.delim("C:/Users/darra/Desktop/Project/HOMER_Active.bed", sep="\t",header=T, stringsAsFactors = FALSE)  


#Column12 is RWPE1_H3K27ac, So this will grep out the Active RWPE1 enhancers as only these will have this mark
HOMER = grep(1,HOMER_Active[,12]) 
HOMER_Active = HOMER_Active[HOMER,]





for(i in 1:nrow(HOMER_Active)){
  if(HOMER_Active$Strand[i] == "*" ) {
    HOMER_Active$Strand[i] = "+"
    }
}

tail(HOMER_Active)

HOMER_Active_RWPE1 = data.frame(HOMER_Active$Chr, HOMER_Active$Start, HOMER_Active$End, HOMER_Active$ChipPeakAnno_ID, HOMER_Active$Width, HOMER_Active$Strand ) #9000(nrow)




colnames(HOMER_Active_RWPE1) = c("chromosome", "starting position", "ending position", "Unique Peak ID", "Width", "Strand" )



write.table(HOMER_Active_RWPE1,"C:/Users/darra/Desktop/Project/HOMER_Active_RWPE1.bed",col.names=T,row.names=F,sep="\t",quote=F)




```

```{r}
Master_Primed <- read.csv("C:/Users/darra/Dropbox/4th_year_project_Darragh_Nimmo/5_Enhancer_Master_Matrix/Output_files/Master_Primed.txt", sep="\t",header=T, stringsAsFactors = FALSE) #170,236


tail(Master_Primed)
Master_Primed = Master_Primed[-170236,]


HOMER = grep(6,Master_Primed[,17]) 
Master_Primed = Master_Primed[HOMER,] #144,092


HOMER = grep(1,Master_Primed[,8]) 
Master_Primed = Master_Primed[HOMER,] #70,341

for(i in 1:nrow(Master_Primed)){
  if(Master_Primed$Strand[i] == "*" ) {
    Master_Primed$Strand[i] = "+"
    }
}


HOMER_Primed_LNCaP = data.frame(Master_Primed$Chr, Master_Primed$Start, Master_Primed$End, Master_Primed$ChipPeakAnno_ID, Master_Primed$Width, Master_Primed$Strand )


colnames(HOMER_Primed_LNCaP) = c("chromosome", "starting position", "ending position", "Unique Peak ID", "Width", "Strand" )

write.table(HOMER_Primed_LNCaP,"C:/Users/darra/Desktop/Project/HOMER_Primed_LNCaP.bed",col.names=T,row.names=F,sep="\t",quote=F)

```

```{r}
Master_Poised <- read.csv("C:/Users/darra/Dropbox/4th_year_project_Darragh_Nimmo/5_Enhancer_Master_Matrix/Output_files/Master_Poised.txt", sep="\t",header=T, stringsAsFactors = FALSE) 



tail(Master_Poised)
Master_Poised = Master_Poised[-2850,]


HOMER = grep(8,Master_Poised[,17]) 
Master_Poised = Master_Poised[HOMER,] 


HOMER = grep(1,Master_Poised[,13]) 
Master_Poised = Master_Poised[HOMER,]

for(i in 1:nrow(Master_Poised)){
  if(Master_Poised$Strand[i] == "*" ) {
    Master_Poised$Strand[i] = "+"
    }
}


HOMER_Poised_RWPE1 = data.frame(Master_Poised$Chr, Master_Poised$Start, Master_Poised$End, Master_Poised$ChipPeakAnno_ID, Master_Poised$Width, Master_Poised$Strand )


colnames(HOMER_Poised_RWPE1) = c("chromosome", "starting position", "ending position", "Unique Peak ID", "Width", "Strand" )

write.table(HOMER_Poised_RWPE1,"C:/Users/darra/Desktop/Project/HOMER_Poised_RWPE1.bed",col.names=T,row.names=F,sep="\t",quote=F)



```


##Post HOMER

```{r}
##Active Enhancers

##denovo LNCaP
Active_LNCaP_motifs_denovo = read.csv("C:/Users/darra/Desktop/Project/HOMER_Active_LNCaP_Output/Active_LNCaP_denovo_Motifs.txt", sep="\t",header=T, stringsAsFactors = FALSE)
dim(Active_LNCaP_motifs_denovo)  #773 6
unique_active_LNCaP_denovo = unique(Active_LNCaP_motifs_denovo[,1])
length(unique_active_LNCaP_denovo)  #530 enhancers with  >= 1 transcription factors binding


##known LNCaP
Active_LNCaP_motifs_known = read.csv("C:/Users/darra/Desktop/Project/HOMER_Active_LNCaP_Output/Active_LNCaP_motifs_known.txt", sep="\t",header=T, stringsAsFactors = FALSE)
dim(Active_LNCaP_motifs_known)  #2940 6
unique_active_LNCaP_known = unique(Active_LNCaP_motifs_known[,1])
length(unique_active_LNCaP_known) #922 enhancers with  >= 1 transcription factors binding


##denovo RWPE1
Active_RWPE1_motifs_denovo = read.csv("C:/Users/darra/Desktop/Project/HOMER_Active_RWPE1_Output_2/Active_RWPE1_motifs_denovo.txt", sep="\t",header=T, stringsAsFactors = FALSE)
dim(Active_RWPE1_motifs_denovo)  #14270 6
unique_active_RWPE1_denovo = unique(Active_RWPE1_motifs_denovo[,1])
length(unique_active_RWPE1_denovo)  #3844 enhancers with  >= 1 transcription factors binding


#Known RWPE1
Active_RWPE1_motifs_known = read.csv("C:/Users/darra/Desktop/Project/HOMER_Active_RWPE1_Output_2/Active_RWPE1_motifs_known.txt", sep="\t",header=T, stringsAsFactors = FALSE)
dim(Active_RWPE1_motifs_known)  #34314    6
unique_active_RWPE1_known = unique(Active_RWPE1_motifs_known[,1])
length(unique_active_RWPE1_known)  #5681 enhancers with  >= 1 transcription factors binding


All_Active_motifs = rbind(Active_LNCaP_motifs_denovo, Active_LNCaP_motifs_known, Active_RWPE1_motifs_denovo, Active_RWPE1_motifs_known)
dim(All_Active_motifs) #52297

unique_all_active_motifs = unique(All_Active_motifs[,1])
length(unique_all_active_motifs) #7417.  So this is the number of active enhancers which are bound by >= 1 transcription factor

 
HOMER_Active_LNCaP <- read.delim("C:/Users/darra/Desktop/Project/HOMER_Active_LNCaP.bed", sep="\t",header=T, stringsAsFactors = FALSE)
dim(HOMER_Active_LNCaP)   #1536  6

HOMER_Active_RWPE1 <- read.delim("C:/Users/darra/Desktop/Project/HOMER_Active_RWPE1.bed", sep="\t",header=T, stringsAsFactors = FALSE)
dim(HOMER_Active_RWPE1)  #8016  6



Master_Importance = read.csv("C:/Users/darra/Dropbox/4th_year_project_Darragh_Nimmo/5_Enhancer_Master_Matrix/Output_files/3_Master_Importance.txt", sep="\t",header=T, stringsAsFactors = FALSE)

All_Active_motifs 
motifs = data.frame(All_Active_motifs$PositionID, All_Active_motifs$Motif.Name)
colnames(motifs) = c("ChipPeakAnno_ID", "TFBS")

total <- merge(Master_Importance, motifs, by="ChipPeakAnno_ID")


Active_motifs = total %>%
  group_by(ChipPeakAnno_ID, enh_state, Chr, Start, End, Width, Strand, LNCaP_H3K4me1, LNCaP_H3K27ac, LNCaP_H3K27me3, RWPE1_H3K4me1
, RWPE1_H3K27ac, RWPE1_H3K27me3, DHS_LNCaP, DHS_RWPE1, STARR_LNCaP, Importance) %>%
  summarise(TFBS = paste(TFBS, collapse= "# "))
  

for(i in 1:nrow(Active_motifs)){
  TF_Number = str_count(Active_motifs$TFBS, '#') + 1 
}
Active_motifs$Number_of_TF = TF_Number
Active_motifs = Active_motifs[,-18]


```


##Primed
```{r}
##Primed Enhancers

##denovo LNCaP
Primed_LNCaP_motifs_denovo = read.csv("C:/Users/darra/Desktop/Project/HOMER_Primed_LNCaP_Output/Primed_LNCaP_motif_denovo.txt", sep="\t",header=T, stringsAsFactors = FALSE)
dim(Primed_LNCaP_motifs_denovo)  #22,383   6
unique_primed_LNCaP_denovo = unique(Primed_LNCaP_motifs_denovo[,1])
length(unique_primed_LNCaP_denovo)  #15,533 enhancers with  >= 1 transcription factors binding


##known LNCaP
Primed_LNCaP_motifs_known = read.csv("C:/Users/darra/Desktop/Project/HOMER_Primed_LNCaP_Output/Primed_LNCaP_motif_known.txt", sep="\t",header=T, stringsAsFactors = FALSE)
dim(Primed_LNCaP_motifs_known)  #334,768  6
unique_primed_LNCaP_known = unique(Primed_LNCaP_motifs_known[,1])
length(unique_primed_LNCaP_known) #57653 enhancers with  >= 1 transcription factors binding


##denovo RWPE1
Primed_RWPE1_motifs_denovo = read.csv("C:/Users/darra/Desktop/Project/HOMER_Primed_RWPE1_Output/Primed_RWPE1_motif_denovo.txt", sep="\t",header=T, stringsAsFactors = FALSE)
dim(Primed_RWPE1_motifs_denovo)  #1,111,621       6
unique_primed_RWPE1_denovo = unique(Primed_RWPE1_motifs_denovo[,1])
length(unique_primed_RWPE1_denovo)  #69645 enhancers with  >= 1 transcription factors binding


#Known RWPE1
Primed_RWPE1_motifs_known = read.csv("C:/Users/darra/Desktop/Project/HOMER_Primed_RWPE1_Output/Primed_RWPE1_motif_known.txt", sep="\t",header=T, stringsAsFactors = FALSE)
dim(Primed_RWPE1_motifs_known)  #1,628,005       6
unique_primed_RWPE1_known = unique(Primed_RWPE1_motifs_known[,1])
length(unique_primed_RWPE1_known)  #73669 enhancers with  >= 1 transcription factors binding


All_Primed_motifs = rbind(Primed_LNCaP_motifs_denovo, Primed_LNCaP_motifs_known, Primed_RWPE1_motifs_denovo, Primed_RWPE1_motifs_known)
dim(All_Primed_motifs) #]3,096,777  6

unique_all_primed_motifs = unique(All_Primed_motifs[,1])
length(unique_all_primed_motifs) #133,121.  So this is the number of active enhancers which are bound by >= 1 transcription factor


HOMER_Primed_LNCaP <- read.delim("C:/Users/darra/Desktop/Project/HOMER_Primed_LNCaP.bed", sep="\t",header=T, stringsAsFactors = FALSE)
dim(HOMER_Primed_LNCaP)  #70341  6
 
HOMER_Primed_RWPE1 <- read.delim("C:/Users/darra/Desktop/Project/HOMER_Primed_RWPE1.bed", sep="\t",header=T, stringsAsFactors = FALSE)
dim(HOMER_Primed_RWPE1)   #73,751  6


Master_Importance = read.csv("C:/Users/darra/Dropbox/4th_year_project_Darragh_Nimmo/5_Enhancer_Master_Matrix/Output_files/3_Master_Importance.txt", sep="\t",header=T, stringsAsFactors = FALSE)

All_Primed_motifs 
motifs = data.frame(All_Primed_motifs$PositionID, All_Primed_motifs$Motif.Name)
colnames(motifs) = c("ChipPeakAnno_ID", "TFBS")

total <- merge(Master_Importance, motifs, by="ChipPeakAnno_ID")
write.table(total,"C:/Users/darra/Desktop/Project/Primed_motif_locations.txt",col.names=T,row.names=F,sep="\t",quote=F)

Primed_motifs = total %>%
  group_by(ChipPeakAnno_ID, enh_state, Chr, Start, End, Width, Strand, LNCaP_H3K4me1, LNCaP_H3K27ac, LNCaP_H3K27me3, RWPE1_H3K4me1
, RWPE1_H3K27ac, RWPE1_H3K27me3, DHS_LNCaP, DHS_RWPE1, STARR_LNCaP, Importance) %>%
  summarise(TFBS = paste(TFBS, collapse= "# "))
  

for(i in 1:nrow(Primed_motifs)){
  TF_Number = str_count(Primed_motifs$TFBS, '#') + 1 
}
Primed_motifs$Number_of_TF = TF_Number
Primed_motifs = Primed_motifs[,-18]


```






##Poised
```{r}
##Poised Enhancers

##denovo LNCaP
Poised_LNCaP_motifs_denovo = read.csv("C:/Users/darra/Desktop/Project/HOMER_Poised_LNCaP_Output/Poised_LNCaP_motifs_denovo.txt", sep="\t",header=T, stringsAsFactors = FALSE)
dim(Poised_LNCaP_motifs_denovo)  #32   6
unique_poised_LNCaP_denovo = unique(Poised_LNCaP_motifs_denovo[,1])
length(unique_poised_LNCaP_denovo)  #12 enhancers with  >= 1 transcription factors binding


##known LNCaP
Poised_LNCaP_motifs_known = read.csv("C:/Users/darra/Desktop/Project/HOMER_Poised_LNCaP_Output/Poised_LNCaP_motifs_known.txt", sep="\t",header=T, stringsAsFactors = FALSE)
dim(Poised_LNCaP_motifs_known)  #91  6
unique_poised_LNCaP_known = unique(Poised_LNCaP_motifs_known[,1])
length(unique_poised_LNCaP_known) #88 enhancers with  >= 1 transcription factors binding


##denovo RWPE1
Poised_RWPE1_motifs_denovo = read.csv("C:/Users/darra/Desktop/Project/HOMER_Poised_RWPE1_Output/Poised_RWPE1_motifs_denovo.txt", sep="\t",header=T, stringsAsFactors = FALSE)
dim(Poised_RWPE1_motifs_denovo)  #1007       6
unique_poised_RWPE1_denovo = unique(Poised_RWPE1_motifs_denovo[,1])
length(unique_poised_RWPE1_denovo)  #180 enhancers with  >= 1 transcription factors binding


#Known RWPE1
Poised_RWPE1_motifs_known = read.csv("C:/Users/darra/Desktop/Project/HOMER_Poised_RWPE1_Output/Poised_RWPE1_motif_known.txt", sep="\t",header=T, stringsAsFactors = FALSE)
dim(Poised_RWPE1_motifs_known)  #6648   6
unique_poised_RWPE1_known = unique(Poised_RWPE1_motifs_known[,1])
length(unique_poised_RWPE1_known)  #934 enhancers with  >= 1 transcription factors binding


All_Poised_motifs = rbind(Poised_LNCaP_motifs_denovo, Poised_LNCaP_motifs_known, Poised_RWPE1_motifs_denovo, Poised_RWPE1_motifs_known)
dim(All_Poised_motifs) #7778  6

unique_all_poised_motifs = unique(All_Poised_motifs[,1])
length(unique_all_poised_motifs) #1051  So this is the number of active enhancers which are bound by >= 1 transcription factor


HOMER_Primed_LNCaP <- read.delim("C:/Users/darra/Desktop/Project/HOMER_Primed_LNCaP.bed", sep="\t",header=T, stringsAsFactors = FALSE)
dim(HOMER_Primed_LNCaP)  #70341  6
 
HOMER_Primed_RWPE1 <- read.delim("C:/Users/darra/Desktop/Project/HOMER_Primed_RWPE1.bed", sep="\t",header=T, stringsAsFactors = FALSE)
dim(HOMER_Primed_RWPE1)   #73,751  6

Master_Importance = read.csv("C:/Users/darra/Dropbox/4th_year_project_Darragh_Nimmo/5_Enhancer_Master_Matrix/Output_files/3_Master_Importance.txt", sep="\t",header=T, stringsAsFactors = FALSE)

All_Poised_motifs 
motifs = data.frame(All_Poised_motifs$PositionID, All_Poised_motifs$Motif.Name)
colnames(motifs) = c("ChipPeakAnno_ID", "TFBS")

total <- merge(Master_Importance, motifs, by="ChipPeakAnno_ID")
write.table(total,"C:/Users/darra/Desktop/Project/Poised_motif_locations.txt",col.names=T,row.names=F,sep="\t",quote=F)

```

```{r}
library(dplyr)
#install.packages("tidyverse")
library(tidyverse)
library(stringr)

total <- read.delim("C:/Users/darra/Desktop/Project/Poised_motif_locations.txt", sep="\t",header=T, stringsAsFactors = FALSE)


poised_motifs = total %>%
  group_by(ChipPeakAnno_ID, enh_state, Chr, Start, End, Width, Strand, LNCaP_H3K4me1, LNCaP_H3K27ac, LNCaP_H3K27me3, RWPE1_H3K4me1
, RWPE1_H3K27ac, RWPE1_H3K27me3, DHS_LNCaP, DHS_RWPE1, STARR_LNCaP, Importance) %>%
  summarise(TFBS = paste(TFBS, collapse= "# "))
  

for(i in 1:nrow(poised_motifs)){
  TF_Number = str_count(poised_motifs$TFBS, '#') + 1 
}
poised_motifs$Number_of_TF = TF_Number
poised_motifs = poised_motifs[,-18]



```

##Doing all of HOMER again 
```{r}













```